name: turnigym
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.0
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  fl_chart: ^1.2.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.0  # <-- Bunu ekle!
  crypto: ^3.0.7
  provider: ^6.1.2
  google_fonts: ^6.1.0
  mobile_scanner: ^7.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/turnigym.png
    - assets/images/cihaz_durumu.png
    - assets/images/kiz.png
    - assets/images/erkek.png
   